"""empty message

Revision ID: 62499fa5bf2e
Revises: 
Create Date: 2018-09-02 15:05:25.290041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62499fa5bf2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    # ### end Alembic commands ###
